// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionFloorPlacementService.Data;

#nullable disable

namespace ProductionFloorPlacementService.Migrations
{
    [DbContext(typeof(ProductionFloorPlacementServiceContext))]
    [Migration("20231205155443_mssql.azure_migration_431")]
    partial class mssqlazure_migration_431
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductionFloorPlacementService.Models.PlacementContractModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductionFloorModelId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologicalEquipmentModelId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologicalEquipmentQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionFloorModelId");

                    b.HasIndex("TechnologicalEquipmentModelId");

                    b.ToTable("PlacementContractModel");
                });

            modelBuilder.Entity("ProductionFloorPlacementService.Models.ProductionFloorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductionFloorModel");
                });

            modelBuilder.Entity("ProductionFloorPlacementService.Models.TechnologicalEquipmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechnologicalEquipmentModel");
                });

            modelBuilder.Entity("ProductionFloorPlacementService.Models.PlacementContractModel", b =>
                {
                    b.HasOne("ProductionFloorPlacementService.Models.ProductionFloorModel", "ProductionFloor")
                        .WithMany()
                        .HasForeignKey("ProductionFloorModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionFloorPlacementService.Models.TechnologicalEquipmentModel", "TechnologicalEquipment")
                        .WithMany()
                        .HasForeignKey("TechnologicalEquipmentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionFloor");

                    b.Navigation("TechnologicalEquipment");
                });
#pragma warning restore 612, 618
        }
    }
}
